# this is for local testing purposes. view /docs/docker-compose.yml for a deployment example.

services:
  atest:
    build:
      context: .
      no_cache: true
    ports:
      - "3001:3000"
    volumes:
      - ./backend/application.conf:/app/application.conf
