
// $2a$12$WmbECJg6GlgFzWZ68i5M9u/s2TLbYIe9nqSCfrfNOhBlire7GeoLe
POST http://{{host}}/auth/login
Content-Type: application/json

{
  "email": "xyron1996@gmail.com",
  "password": "123123"
}

###

GET http://{{host}}/auth/me

###

GET http://{{host}}/me

###

GET http://{{host}}/auth/logout

###

POST http://{{host}}/auth/register
Content-Type: application/json

{
  "email": "test@test.de",
  "password": "a123ABCd2e!",
  "confirm_password": "a123ABCd2e!"
}
