###

POST {{host}}/auth/login
Content-Type: application/json

{
  "email": {{email}},
  "password": {{password}}
}

###

GET {{host}}/auth/me

###

GET {{host}}/auth/logout

###

POST {{host}}/auth/register
Content-Type: application/json

{
  "email": "test@test.de",
  "password": "a123ABCd2e!",
  "confirm_password": "a123ABCd2e!"
}

###

GET {{host}}/setup

