
// $2a$12$WmbECJg6GlgFzWZ68i5M9u/s2TLbYIe9nqSCfrfNOhBlire7GeoLe
POST {{url}}/auth/login
Content-Type: application/json

{
  "email": "xyron1996@gmail.com",
  "password": "123123"
}

###

GET {{url}}/auth/me

###

GET {{url}}/me

###

GET {{url}}/auth/logout

###

POST {{url}}/auth/register
Content-Type: application/json

{
  "email": "test@test.de",
  "password": "a123ABCd2e!",
  "confirm_password": "a123ABCd2e!"
}
