POST {{host}}/{{project}}/dummy

###

GET {{host}}/{{project}}/events/catalog

###

GET {{host}}/{{project}}/events/parquet/export

###

GET {{host}}/{{project}}/events/parquet/months/checksums

###

GET {{host}}/{{project}}/events?timestamp__gt=2024-06-19T18:29:04.300Z

###

