POST http://{{host}}/{{project}}/dummy

###

GET http://{{host}}/{{project}}/events/parquet/checksums

###

GET http://{{host}}/{{project}}/events/parquet/export

###

GET http://{{host}}/{{project}}/events/parquet/months/checksums

###
