GET http://{{host}}/{{project}}/insights

###
POST http://{{host}}/{{project}}/insights
Content-Type: application/json

{
  "type": "Trend",
  "name": "New Insight 11",
  "config": {
    "series": [],
    "type": "Trend",
    "data": {
      "timeBucket": "Daily",
      "duration": "4weeks"
    }
  }
}

###

GET http://{{host}}/{{project}}/insights/18

###

PUT http://{{host}}/{{project}}/insights/2
Content-Type: application/json

{
  "name": "Updated Insight"
}

###

DELETE http://{{host}}/{{project}}/insights/1

###

