GET {{url}}/insights

###
POST {{url}}/insights
Content-Type: application/json

{
  "name": "New Insight 11",

  "description": "This is a new insight",
  "series": []
}

###

GET {{url}}/insights/12

###

PUT {{url}}/insights/1
Content-Type: application/json

{
  "name": "Updated Insight",
  "description": "This insight has been updated",
  "series": [
    {
      "name": "Updated Series",
      "query": {
        "select": [
          "column2"
        ],
        "from": "table2"
      }
    }
  ]
}

###

DELETE {{url}}/insights/1

###

