POST {{host}}/projects
Content-Type: application/json

{
  "name": "test"
}

###
GET {{host}}/projects

###

POST {{host}}/{{project}}/settings
Content-Type: application/json

[
  {
    "key": "name",
    "value": "updated name2"
  },
  {
    "key": "partition",
    "value": ""
  }
]
