###

POST http://{{host}}/auth/login
Content-Type: application/json

{
  "email": "test@test.de",
  "password": "a123ABCd2e!"
}

###

GET http://{{host}}/auth/me

###

GET http://{{host}}/auth/logout

###

POST http://{{host}}/auth/register
Content-Type: application/json

{
  "email": "test@test.de",
  "password": "a123ABCd2e!",
  "confirm_password": "a123ABCd2e!"
}

###

GET http://{{host}}/setup

