name: Build Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-arm:
    runs-on: [self-hosted, linux, ARM64]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image for ARM
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/arm64
          provenance: false
          build-args: |
            GOOS=linux
            GOARCH=arm64
          tags: |
            ghcr.io/xz3dev/quacklytics/arm64:latest
            ghcr.io/xz3dev/quacklytics/arm64:${{ github.run_id }}-${{ github.sha }}
          file: Dockerfile

  build-amd:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image for AMD
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64
          provenance: false
          build-args: |
            GOOS=linux
            GOARCH=amd64
          tags: |
            ghcr.io/xz3dev/quacklytics/amd64:latest
            ghcr.io/xz3dev/quacklytics/amd64:${{ github.run_id }}-${{ github.sha }}
          file: Dockerfile
