name: Build Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: [self-hosted, linux, ARM64]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image for ARM
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        push: true
        platforms: linux/arm64
        provenance: false
        tags: |
          ghcr.io/xz3dev/quacklytics/main:latest
          ghcr.io/xz3dev/quacklytics/main:${{ github.run_id }}-${{ github.sha }}
        file: Dockerfile
